# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb1ea078ddcfaa41d450e21de475223dace4aa6605e4dab2832cda3ca08ead5d7198d85f5b666e522296936f55b53241c76b3bf03522c0f955ae3237d133b8b

test:
  secret_key_base: d696425f86a2166ae2b7a55105d33edae06eede546444f51b19b4ed2eaf1e3bd4c5514b4550ce89a78a4c8599eeef3dca42fb5398d36740cedc1ed4c2da6931c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
